### ISSUE TITLE
Emoji who are a ZWJ combination don't get converted from colons to unified with a skin-tone

### ISSUE THREAD

**Issue by eramdam** [iamcal/js-emoji#101]
Sorry for the rather verbose title. Here's a JSbin showing the bug

http://jsbin.com/zagenas/edit?html,js,output

Tried under Chrome and Safari on macOS 10.12.6
![image](https://user-images.githubusercontent.com/1409924/33245566-6f86afc6-d2be-11e7-9d41-24a8f8fc5644.png)

**Comment by iamcal** [comment]
good catch! fixed on trunk

this had never worked as intended - for any emoji with a skin tone, the unified output always added the skin tone codepoint last, regardless of whether it was defined or not. this worked for _most_ ZWJ sequences, but not ones added in Emoji 4.0 and later. Not sure how I never noticed this before.

**Comment by eramdam** [comment]
No worries! Thanks for the quick fix on a Sunday 😁
