### ISSUE TITLE
How to use this with React

### ISSUE THREAD

**Issue by mubaris** [iamcal/js-emoji#105]

**Comment by xanderberkein** [comment]
I'm using it like this without a problem:

```javascript
import EmojiConverter from 'emoji-js';
const emoji = new EmojiConverter();
```

**Comment by mubaris** [comment]
I get that. Is there any way to render emojis without using `dangerouslySetInnerHTML`. That's my question!

**Comment by xanderberkein** [comment]
No, I'm afraid not. Using `dangerouslySetInnerHTML` is fine though, as long as the input is properly sanitized.

If you are only interested in converting colon-notation to unicode emoji's (e.g. `:cat:` to 🐱), you can render the html yourself by using the `replace_emoticons` function of the library. You can't convert emoji's to image assets this way.

```javascript
const string = YOUR_STRING;

// inside render:
<div>{emoji.replace_emoticons(string)}</div>
```

**Comment by mubaris** [comment]
Too bad that I can't convert unicode emojis to images :disappointed:

**Comment by xanderberkein** [comment]
Yeah, you'll need to stick to `dangerouslySetInnerHTML` for that.
