### ISSUE TITLE
Auto-downcase in colon syntax?

### ISSUE THREAD

**Issue by backspace** [iamcal/js-emoji#109]
Hello, thanks for this library! I’m a user of it through [Signal Desktop](https://github.com/signalapp/Signal-Desktop), it’s great for me to quickly type emoji.

I’ve found myself sending funny messages though when I type something like `:Smile:` by mistake rather than `:smile:`. What do you think of searching with downcased text within colons when looking for matching emoji name? Maybe it could be configurable.

If you think this is a good idea, I could make a PR.

**Comment by backspace** [comment]
hmm upon looking at the tests, I see that `allow_caps` is already a flag! I didn’t notice that earlier. I think it’s probably not worth having another flag with almost-identical functionality, perhaps? I could ask that Signal Desktop have that flag turned on, instead.

I could still produce a PR if you think it makes sense, but maybe `allow_caps = true` could be the default instead?

**Comment by iamcal** [comment]
that's a good idea :)
