### ISSUE TITLE
Some emoji aren't working with skin tone modifiers

### ISSUE THREAD

**Issue by skoda** [iamcal/js-emoji#111]
With the latest emoji.js and library of images, some emoji aren't working with the skin tone modifier that should. These don't appear to be working and display as the base emoji and the separate skin-tone modifier:

☝🏻✌🏻🖐🏻✍🏻🕴🏻

**Comment by iamcal** [comment]
ahh, this was fixed in emoji-data in v4.0.1, but i never cut a new release of js-emoji. i will do that shortly

https://github.com/iamcal/emoji-data/issues/105,

**Comment by iamcal** [comment]
This is now fixed in v3.4.1

**Comment by dallrigo** [comment]
@iamcal Some emoji aren't working still. They are duplicated with a comma in between.

Example, taken from the demo website:

:male-police-officer::skin-tone-4:

<img width="47" alt="screen shot 2018-08-01 at 01 55 39" src="https://user-images.githubusercontent.com/5247586/43501955-93bb734e-952e-11e8-9764-b0175ad0f38a.png">
