### ISSUE TITLE
Some emoji with skin-tone get duplicated when converted to unified representation

### ISSUE THREAD

**Issue by eramdam** [iamcal/js-emoji#113]
Following up on my [comment](https://github.com/iamcal/js-emoji/issues/111#issuecomment-413306558) in #111. I managed to find a list of the emoji that reproduce my case.

Given the following code:

```js
import EmojiConvertor from 'emoji-js';

function buildEmojiConvertor() {
  const result = new EmojiConvertor();

  result.img_sets.apple.path = emojiUrl;
  result.img_sets.apple.sheet = emojiSheetUrl;
  result.use_sheet = true;
  result.img_set = 'apple';

  return result;
}

function unifiedToShortcode(source) {
  const convertor = buildEmojiConvertor();
  convertor.colons_mode = true;
  return convertor.replace_emoticons(convertor.replace_unified(source));
}
```

And the following shortcodes

<details>

```
:man-running::skin-tone-2:
:man-surfing::skin-tone-2:
:man-swimming::skin-tone-2:
:man-lifting-weights::skin-tone-2:
:man-golfing::skin-tone-2:
:male-police-officer::skin-tone-2:
:blond-haired-man::skin-tone-2:
:man-wearing-turban::skin-tone-2:
:male-construction-worker::skin-tone-2:
:woman-tipping-hand::skin-tone-2:
:male-guard::skin-tone-2:
:woman-getting-massage::skin-tone-2:
:woman-getting-haircut::skin-tone-2:
:male-detective::skin-tone-2:
:woman-gesturing-no::skin-tone-2:
:woman-gesturing-ok::skin-tone-2:
:man-bowing::skin-tone-2:
:woman-raising-hand::skin-tone-2:
:woman-frowning::skin-tone-2:
:woman-pouting::skin-tone-2:
:man-rowing-boat::skin-tone-2:
:man-biking::skin-tone-2:
:man-mountain-biking::skin-tone-2:
:man-walking::skin-tone-2:
:man_in_steamy_room::skin-tone-2:
:woman_climbing::skin-tone-2:
:woman_in_lotus_position::skin-tone-2:
:female_mage::skin-tone-2:
:female_fairy::skin-tone-2:
:female_vampire::skin-tone-2:
:merman::skin-tone-2:
:male_elf::skin-tone-2:
:man-bouncing-ball::skin-tone-2:
```

</details>

We get the following result when calling `unifiedToShortcode` on all of those

<details>

```
🏃🏻‍♂️,🏃🏻
🏄🏻‍♂️,🏄🏻
🏊🏻‍♂️,🏊🏻
🏋🏻‍♂️,🏋🏻
🏌🏻‍♂️,🏌🏻
👮🏻‍♂️,👮🏻
👱🏻‍♂️,👱🏻
👳🏻‍♂️,👳🏻
👷🏻‍♂️,👷🏻
💁🏻‍♀️,💁🏻
💂🏻‍♂️,💂🏻
💆🏻‍♀️,💆🏻
💇🏻‍♀️,💇🏻
🕵🏻‍♂️,🕵🏻
🙅🏻‍♀️,🙅🏻
🙆🏻‍♀️,🙆🏻
🙇🏻‍♂️,🙇🏻
🙋🏻‍♀️,🙋🏻
🙍🏻‍♀️,🙍🏻
🙎🏻‍♀️,🙎🏻
🚣🏻‍♂️,🚣🏻
🚴🏻‍♂️,🚴🏻
🚵🏻‍♂️,🚵🏻
🚶🏻‍♂️,🚶🏻
🧖🏻‍♂️,🧖🏻
🧗🏻‍♀️,🧗🏻
🧘🏻‍♀️,🧘🏻
🧙🏻‍♀️,🧙🏻
🧚🏻‍♀️,🧚🏻
🧛🏻‍♀️,🧛🏻
🧜🏻‍♂️,🧜🏻
🧝🏻‍♂️,🧝🏻
⛹🏻‍♂️,⛹🏻
```

</details>

Using `emoji-js@3.4.1` on npm

**Comment by dallrigo** [comment]
These emojis contain two unicode sequences as options for each skin tone variation, according to the `variations_data` object. Whenever this is set inside `find_image` method at line 468, the result comes as an array, although the expected result would be a string. Therefore a duplicated representation separated by a comma (as the string representation of an array).

I couldn't understand why these two options are there in the first place, fallback maybe?

Anyway, a quick fix could be checking if the result is an array, and then select the first item only. Or cleaning up the `variations_data` object removing the duplicated unicode representations.

@iamcal please correct me if I'm wrong here.

**Comment by iamcal** [comment]
this is exactly right - some emoji have multiple codepoint sequences that map to the same shortcode (related to obsoleted gender-neutral versions. this is important when you're mapping in the opposite direction that you're doing here. ultimately the variants list is always an array, just useful a single-element one, so it works by accident. the fix was to change `var_data[4]` to `var_data[4][0]` inside `find_image()`. i've added a test to avoid this breaking in the future too

this fix is on the emoji_13.1 branch which will land on trunk soon
