### ISSUE TITLE
emoji-data dependency

### ISSUE THREAD

**Issue by GRBurst** [iamcal/js-emoji#114]
Hey there 😄,

this project depends on emoji-datasource and hence, the dependent node emoji-datasource folder contains some emoji sheets.

However, when I am using these sheets, the calculated background positions are wrong, resulting in positions in between multiple icons. The files that are provided differ in size from the emoji-datasource, too.

For me it is possible to circumvent this problem by adding a datasource dependency explicitly (e.g. 4.1.0), but I suggest to update the dependency in this project.

Kind regards

**Comment by iamcal** [comment]
master now tracks the latest emoji-datasource release (4.1.0). i will be cutting a new release version of emoji-js shortly
