### ISSUE TITLE
How to get the utf-8 character 👾👾 equivalent to a Github emoji automatically?

### ISSUE THREAD

**Issue by monperrus** [iamcal/js-emoji#117]
I would like to know the utf-8 equivalent of `:heart:` ♥ or `:space_invader:` 👾.

How to get the utf-8 character equivalent to a Github emoji automatically?

```
:heart: -> U+2764
:space_invader: -> U+1F47E
```

Thanks!

**Comment by iamcal** [comment]
Set `emoji.replace_mode = 'unified';` and the raw unicode codepoints will be inserted

**Comment by monperrus** [comment]
thanks.
