### ISSUE TITLE
How is emoji.prototype.data determined/calculated?

### ISSUE THREAD

**Issue by adeopura4** [iamcal/js-emoji#118]
I am trying to determine how emoji.prototype.data is calculated in the file emoji.js. I am trying to use the latest from emoji-data (https://github.com/iamcal/emoji-data/blob/master/sheets-indexed-128/sheet_twitter_32_indexed_128.png) and the positions are different. For instance, the "atm" is at 11,45 in the new sheet, but it is as 12,4 in the new sheet. Thank you.

**Comment by iamcal** [comment]
the master of js-emoji is using v4.0.4 of emoji-data, which is one release behind latest. you can find the correct matching sheets at https://github.com/iamcal/emoji-data/tree/v4.0.4
