### ISSUE TITLE
Update emoji-datasource to 4.1.0

### ISSUE THREAD

**Issue by jfcere** [iamcal/js-emoji#119]
Hi there,

Really like the library but i was wondering if it is still maintained?
Any chance we can get an update to increase emoji-datasource dependency to 4.1.0?

I could submit a PR but I noticed some PRs have been opened for more than 2 years...
Although I see you are still maintaining emoji-datasource repository 🤔 

@iamcal with all respect and knowing you might be a busy guy, if I follow the instruction in the build folder to update emoji-data dependency and rebuild the lib are you going to review and merge it?

**Comment by jfcere** [comment]
I took a shot... if there anything I can do to help or correction you want me to do, don't hesitate as I would be happy to contribute.

**Comment by jfcere** [comment]
@iamcal awesome, thx for the follow-up!

**Comment by iamcal** [comment]
i'll be cutting a new release shortly - thank you for your patience!
