### ISSUE TITLE
Facing incorrect Emoji position 

### ISSUE THREAD

**Issue by Haribabu1692** [iamcal/js-emoji#131]
<img width="249" alt="Screen Shot 2020-06-18 at 4 14 06 PM" src="https://user-images.githubusercontent.com/48591365/85011266-e8537280-b17e-11ea-88ac-49ac8966aaf0.png">

Steps followed : 
1. Bundled js and css files 
2. used below mentioned code 
     var emoji = new EmojiConvertor();
     emoji.img_set = 'apple';
     emoji.use_sheet = true;
     emoji.replace_mode = 'css';
     emoji.img_sets.apple.sheet = "/images/sheet_apple_16.png";
     emoji.replace_colons(text);

How can i solve this ? 
do i need to have seperate data[] object for different size sheets like 16, 20 , 32 and 64 etc..?

**Comment by iamcal** [comment]
Are you using the correct version of the images for the version of this library you're using? They need to match, otherwise images will be in the wrong positions and the sheet will be the wrong size (number of columns and rows)
