### ISSUE TITLE
Merge & Release of the v12 branch

### ISSUE THREAD

**Issue by etienne-robert-erasys** [iamcal/js-emoji#135]
Hey there!

First of all, amazing work on `emoji-data` and `js-emoji` 🙇 
The version on the `v12` branch looks great and includes Emoji v12 😃
Are you planning to merge and release it any time soon?
It would be fantastic for both me and my company 😁

**Comment by etrobert** [comment]
Some complex emojis like 🧑🏾‍🤝‍🧑🏼 from Emoji 13 throw an error on branch `v12`

![image](https://user-images.githubusercontent.com/12083026/109994987-25ac6000-7d0e-11eb-8ea0-22ce1463ef08.png)

**Comment by iamcal** [comment]
Emoji 13.1 has now been merged
