### ISSUE TITLE
replace_mode img not working

### ISSUE THREAD

**Issue by krajcikondra** [iamcal/js-emoji#152]
Hi,

when I use replace_mode img
```
    emojiConvertor.replace_mode = 'img';
    emojiConvertor.img_set = 'google';
    emojiConvertor.replace_colons(msgHtml);
```

I get output output like this:

```
<span class="emoji emoji-sizer" style="background-image:url(/emoji-data/img-google-64/1f600.png)" data-codepoints="1f600"></span>
```

**Comment by iamcal** [comment]
Thanks for reporting this - turns out this has never worked as documented and instead needed a different property to be set, which was used in the tests and not in the docs. Apologies! This is fixed in v3.7.0
