### ISSUE TITLE
Unicode emoji doesn't work for Windows 7+

### ISSUE THREAD

**Issue by TheDecryptor** [iamcal/js-emoji#16]
OS X and iOS aren't the only 2 OSs that ship with an Emoji font, Windows 8+ does as well (And it was backported to Windows 7), as it stands the script unnecessarily converts the emoji to images for these platforms when they're capable of displaying them.

**Comment by iamcal** [comment]
the patch for this landed some time ago: https://github.com/iamcal/js-emoji/commit/3ca22c79bb93427cf33cd62982b93384e6a974a9
