### ISSUE TITLE
function replace_emoticons() doesn't replace emoticons at the very start or end of line

### ISSUE THREAD

**Issue by zpovednicar** [iamcal/js-emoji#160]
`:D :D :D`

Above line, with no whitespace at the start/end, renders only middle one emoticon, despite if it is single-line string or if that line is in the middle of a text block.

**Comment by iamcal** [comment]
I added a test in PR #161, but it currently passes. Can you share your example code where it fails?

**Comment by zpovednicar** [comment]
Wow, what a quick reply, huge respect, especially on Friday. It pushed me to sit down right away and to find that problematic comment with erroneous parsing, only to figure out it was actually bug in our codebase - it is just new frontend layer over an ancient web, and it got the text from the `innerHTML` property  instead of `innerText` (so, sometimes there was unpredictable `&nbsp;` instead of space character).

I am very sorry for that false alarm. Thank you very much, man, have a nice weekend!

**Comment by iamcal** [comment]
No worries at all! There are definitely bugs hiding in the code somewhere. Thank you for reporting :)
