### ISSUE TITLE
Typo error

### ISSUE THREAD

**Issue by RealWorldEdits376W** [iamcal/js-emoji#162]
There is a typo error in the images section. The second line of this section, just above the code snippet is written as, "This value is the used as a lookup in the emoji.img_sets property, which defines each set."
There are two ways to correct this line because it totally depends on what the writer wants to write.
The corrected line could be:
"This value is used as a lookup in the emoji.img_sets property, which defines each set." (Here second 'the' is removed in the line).
"This value is **then** used as a lookup in the emoji.img_sets property, which defines each set." (Here second 'the' is replaced with 'then').

Thank you.

**Comment by iamcal** [comment]
Fixed in #163
