### ISSUE TITLE
Pin versions with bower.

### ISSUE THREAD

**Issue by ggozad** [iamcal/js-emoji#25]
Please include a bower.json making it easy to pin versions. I was bitten by ``img_path`` being replaced by the new ``img_sets``.

**Comment by iamcal** [comment]
i don't know what this means, but would be happy to merge a PR

**Comment by ggozad** [comment]
I am sorry, I am assuming too much I guess.
Here's how you would create a package with bower http://bower.io/docs/creating-packages/ . It basically comes down to you including a bower.json with metadata on your package. Lots of us manage their js dependencies through bower by specifying the name of the package, js-emoji in your case and the released version. If you later update he package and make changes that would break (such as replacing mg_path by img_sets) the apps depending on the older version would not be affected.

I will be happy to make a PR, it's just one son file, if you think you could keep up with increasing version numbers and maintaining the package.

**Comment by iamcal** [comment]
it's now registered, along with semvar tagging.

you can get the old behavior back with `1.0.0` or follow the new stuff with `2.0.0-alpha1`

**Comment by ggozad** [comment]
Awesome, keep up the good work.
