### ISSUE TITLE
npm support

### ISSUE THREAD

**Issue by bigblind** [iamcal/js-emoji#28]
Could you put js-emoji on npm as well? It'd be cool if we could keep track of js-emoji versions the same way we do with our other packages. (we'd prefer not to add bower just for js-emoji).

**Comment by iamcal** [comment]
sure - send a pull request?

**Comment by suprMax** [comment]
@iamcal there's nothing to change in the code, just run `npm publish`

**Comment by iamcal** [comment]
I am unable to publish the package as it's too large (~90MB) and just breaks npm. Because it contains the emoji images, it's hard to make it a lot smaller. i'll try stripping more of the source images and see if it will upload then.

**Comment by iamcal** [comment]
nope, just times out again (51MB now). i'm not sure what to do, since the js-library needs the correct rev of the images to work. npm does not seem like the correct mechanism for distributing 50MB of images, so maybe some workflow that tars the images and puts them elsewhere?

**Comment by iamcal** [comment]
this is being fixed in the emoji-data repo by packaging just the spritesheets. once that works, i can make that a dependency

**Comment by jmeas** [comment]
:+1:

Sounds like you've got it from here, @iamcal, but if anything comes up, lmk and I'd be happy to help get this resolved.

**Comment by jmeas** [comment]
Any updates, or need any help, @iamcal? :) I'd be willing to put in some time to get this worked out, if there's anything I can do.

**Comment by MaxLeiter** [comment]
Bump?

**Comment by iamcal** [comment]
sorry, i just don't use npm. patches welcome

**Comment by MaxLeiter** [comment]
You can't submit a patch - you need to install npm, run 'npm init', fill out the relevant fields, and run 'npm publish'

**Comment by jmeas** [comment]
@MaxLeiter did you read the above comments? He tried, and it was timing out. It seems like we'll need some source updates before the request can go through. Would you have time to try your hand at making the changes @iamcal suggested above?

**Comment by blizzo521** [comment]
FWIW I was just having some trouble with yarn hanging while installing the package and I did a `yarn cache clean` and then `yarn install` was able to install js-emoji without issues.  Yarn is just a wrapper for NPM, so maybe this issue is resolved?

**Comment by Redsandro** [comment]
Workaround to at least get this require'd:

`node_modules/js-emoji/index.js`:
```
module.exports = path/to/bower/js-emoji
```

Then copy `package.json` to that directory.

**Comment by Redsandro** [comment]
@iamcal can you publish this without the `emoji-data` submodule?
This way we can use the data in `lib/emoji.js` through dependency management.

E.g.:
1. Empty the submodule directory (or temporary move it away)
1. `npm publish`

**Comment by jmeas** [comment]
Hmmm...it seems I'm unable to get this package installed from a git SHA. I went back to an old project, cleared node_modules, and tried to reinstall. It just hangs. I'm using the same version of Node and npm as before.

Logs:

```sh
npm verb checkoutTreeish git+https://github.com/iamcal/js-emoji.git#65bb0c504efc6dd875fb251b77e6f27e84e67d1a checkout Note: checking out '65bb0c504efc6dd875fb251b77e6f27e84e67d1a'.
npm verb checkoutTreeish
npm verb checkoutTreeish You are in 'detached HEAD' state. You can look around, make experimental
npm verb checkoutTreeish changes and commit them, and you can discard any commits you make in this
npm verb checkoutTreeish state without impacting any branches by performing another checkout.
npm verb checkoutTreeish
npm verb checkoutTreeish If you want to create a new branch to retain commits you create, you may
npm verb checkoutTreeish do so (now or later) by using -b with the checkout command again. Example:
npm verb checkoutTreeish
npm verb checkoutTreeish   git checkout -b <new-branch-name>
npm verb checkoutTreeish
npm verb checkoutTreeish HEAD is now at 65bb0c5... cut release 3.0.2
npm info git [ 'submodule', '-q', 'update', '--init', '--recursive' ]
```

Versions:

> Now using node v6.7.0 (npm v3.10.3)

And lastly, the dep from package.json:

```
"js-emoji": "git+https://github.com/iamcal/js-emoji.git#65bb0c504efc6dd875fb251b77e6f27e84e67d1a",
```

Is anyone else having this issue? 🤔

**Comment by iamcal** [comment]
it's now on npm as `emoji-js`, not including any of the images.

my intention is to split the images into their own npm packages, maybe one per image set

**Comment by iamcal** [comment]
that work is tracked here: https://github.com/iamcal/emoji-data/issues/84

**Comment by jmeas** [comment]
@iamcal , I just now switched over to the npm package. It works great. Just wanted to say thanks!
