### ISSUE TITLE
Different color variations of emoji not appearing

### ISSUE THREAD

**Issue by virajsoni** [iamcal/js-emoji#30]
Hello @iamcal,
First of all, its a amazing plugin. Thanks.

I've been using this plugin and it shows all the emoji's perfectly except the new Apple color emoji variations

Basically, I'm looping it through a series of strings containing the Unicode for the emoji. It converts almost all the Unicode strings except the new Apple color variations.

Here's the code which is generating the emoji's

emoji.img_path = '../emoji/img-apple-64/';
emoji.sheet_path = '../emoji/sheet_apple_64.png';
emoji.use_sheet = true;
emoji.init_env();
var auto_mode = emoji.replace_mode;

var thoughtString = jsonTextWithMarkup;
thoughtString = emoji.replace_unified(thoughtString);

Here's a screenshot of what is being replaced:
![screenshot](https://cloud.githubusercontent.com/assets/5259276/7720047/342a7b28-fee6-11e4-915c-2abae55ca01c.png)

**Comment by iamcal** [comment]
the `replace_unified()` method did not support skin-tones until PR #38, but this should now work correctly.
