### ISSUE TITLE
replace_unified doesn't work with a few emoji's when converted from colons

### ISSUE THREAD

**Issue by xBytez** [iamcal/js-emoji#43]
When I convert emoji's like :man-kiss-man: /  :man-man-girl-girl: : etc to Unified/Unicode (:man-man-girl-girl:  -> 👨‍👨‍👧‍👧) that works fine. 

But if I then execute replace_unified on 👨‍👨‍👧‍👧 it doesn't work. 
It shows ![Example-Broken](https://xbytez.eu/i/d/2015-08-26_23-52-28.png) 

instead of 

![Example-Working](https://xbytez.eu/i/d/2015-08-26_23-53-25.png) 

(it does work when I paste that Unicode on Slack though). 

Is this a bug in the code or am I doing it wrong?

**Comment by iamcal** [comment]
i suspect this is a genuine bug - i need to correctly order the replacement candidates to match longest first,

**Comment by xBytez** [comment]
alright! please let me know if you have any updates on this.

**Comment by xBytez** [comment]
Thanks for the quick fix! You rock! ;)
