### ISSUE TITLE
Add ability to force replace_mode

### ISSUE THREAD

**Issue by olegshilov** [iamcal/js-emoji#45]
Hi. I stuck on replacing emoji to unified sign.
When i set `emoji.replace_mode = 'unified'` before replace, it always changed in `emoji.init_env`
Any help will be appreciated.

**Comment by acarr** [comment]
@olegshilov I just ran into the same issue. Hacked it by setting the `emoji.inits.env = 1` effectively telling the library that the environment has been set, don't change it. Then I just set the replace mode.

```
var emoji = new EmojiConvertor();
emoji.inits.env = 1;
emoji.replace_mode = 'unified';
```

**Comment by iamcal** [comment]
alternatively you can do:

    var emoji = new EmojiConvertor();
    emoji.init_env();
    emoji.replace_mode = 'unified';

I will make this easier and document it in a future version.

**Comment by iamcal** [comment]
now that the library requires you to instantiate an object yourself, we can call `init_env()` automatically. we didn't previously do this because not all environment was available when the js file was loaded, but we don't have that issue anymore.

trunk has been updated to fix this
