### ISSUE TITLE
Minified file does not display proper emoji's

### ISSUE THREAD

**Issue by virajsoni06** [iamcal/js-emoji#46]
Hi @iamcal,

I updated my emoji sheets and images to the latest files. Since then when I try to use the minified version of emoji.js, it will not show the correct emoji.

I'm using it with requirejs. First I thought it must be some issue caused by r.js optimizer but I tested it with both optimized and unoptimized versions.

Here are 2 screenshots of with and without minified js

Minified:
![emoji_minified](https://cloud.githubusercontent.com/assets/13236286/10571898/03126ea4-7661-11e5-858f-27f0114d9f66.png)

No minification:
![emoji_no_minification](https://cloud.githubusercontent.com/assets/13236286/10571899/0318ec7a-7661-11e5-8f35-6ac8d0fb7dae.png)

**Comment by nicklaros** [comment]
I'm having this issue too

**Comment by kainosnoema** [comment]
We were just having this problem too with UglifyJS2, and the solution was to tell the minifier to not output literals (`--ascii-only` option: https://github.com/mishoo/UglifyJS2/issues/490). There may be an option like that in r.js as well, I'm not sure.

The offending code in `js-emoji` is this line: https://github.com/iamcal/js-emoji/blob/master/lib/emoji.js#L316. The string `")(\ud83c[\udffb-\udfff])?"` is output by the minifier as `")(�[�-�])?"`, which doesn't create the same regular expression, preventing a match with the skin tone sequences.

**Comment by iamcal** [comment]
patched on trunk and will go out in next release

the existing tests failed when run against the minified version; they now pass
