### ISSUE TITLE
emoji.img_path doesn't change path

### ISSUE THREAD

**Issue by levelsio** [iamcal/js-emoji#47]
```
$(function() {
				emoji.img_path = "https://server.com/assets/emoji";
				alert(emoji.replace_colons(':smile:'));
			});
```

Should return

```
<span class="emoji emoji-sizer" style="background-image:url('https://server.com/assets/emoji/img-apple-64/1f604.png')"></span>
```

But instead returns:

```
<span class="emoji emoji-sizer" style="background-image:url(/emoji-data/img-apple-64/1f604.png)"</span>
```

Also the filenames (img-apple-64) etc. don't seem to match up with the suggested emoji set:

```
https://github.com/github/gemoji/tree/master/images/emoji/unicode
```

which has hex-type filenames like 1f19a.png.

I'm probably doing some things completely wrong.

**Comment by sheyooo** [comment]
just went through source code i dont see that... 
Could you point me to where you saw that?

**Comment by Pmmlabs** [comment]
I confirm this issue, it's not possible to specify the server for loading images.
The text of source code simply doesn't contain `img_path`.
Temporary workaround is
```JS
emoji.img_sets[emoji.img_set].path = 'https://raw.githubusercontent.com/github/gemoji/master/images/emoji/unicode/';
```

**Comment by sheyooo** [comment]
@Pmmlabs @levelsio try it this way instead 
and if that doesnt work make sure you have access to the emoji variable maybe inside the emoji init functiton

`emoji.img_sets[emoji.img_set]['path'] = 'https://raw.githubusercontent.com/github/gemoji/master/images/emoji/unicode/';`

**Comment by nikolas** [comment]
I've run into this problem too. Thanks for the fix, I'm doing this:

```js
emoji.img_path = '/media/emoji-data/img-apple-64/';
emoji.img_sets[emoji.img_set].path = emoji.img_path;
```

**Comment by iamcal** [comment]
the docs were wrong and have now been updated - sorry!
