### ISSUE TITLE
Did v3 break everything?

### ISSUE THREAD

**Issue by eramdam** [iamcal/js-emoji#55]
I used this lib in v2 and it was working great, I tried v3 and even on the demo the substitution seems wrong...

![screen shot 2016-05-15 at 8 59 15 pm](https://cloud.githubusercontent.com/assets/1409924/15280019/f458a774-1adf-11e6-9b9f-010e529f6580.png)

**Comment by iamcal** [comment]
the demo was pointing to the wrong version of the images - it's now pointing to the correct one. you must make sure you're using the emoji-data submodule that's inside the `build/` directory, rather than the master of the `emoji-data` repo

**Comment by eramdam** [comment]
Oh ok. Thanks and sorry for the alarming title 😛

**Comment by iamcal** [comment]
no worries, i had not realized it was broken
