### ISSUE TITLE
Updated docs

### ISSUE THREAD

**Issue by jamesplease** [iamcal/js-emoji#59]
It looks like the docs could use some sprucing up. The options documented seem incomplete, and feature like jquery.emoji.js aren't mentioned at all atm.

I'd be down to help get this library fully documented if you think I could help out, @iamcal!

**Comment by iamcal** [comment]
yeah, they are incomplete and often wrong :(

**Comment by divdax** [comment]
**+1**

Please update the docs with some working examples to understand how this library work.

**Comment by iamcal** [comment]
docs were updated last year and should now be accurate (and useful)
