### ISSUE TITLE
Update build directory of emoji-data

### ISSUE THREAD

**Issue by jmeas** [iamcal/js-emoji#63]
The SHA of emoji-data that is referenced by this project is a commit that doesn't take into account https://github.com/iamcal/emoji-data/pull/51, so [Travis builds are still failing](https://travis-ci.org/jmeas/moolah/builds/135200756). Would it be possible to cut a release/update that SHA? I think that's the last thing we need to get this all worked out :) 

**Update:** Confirmed – that fixes it! [Passing build here](https://travis-ci.org/jmeas/moolah/builds/135202743) which relies on a fork.

**Comment by iamcal** [comment]
i'm hesitant to do this until i cut a new release of emoji-data, but that should happen pretty soon

**Comment by jmeas** [comment]
Sounds good to me. Thanks!

**Comment by iamcal** [comment]
emoji-data 2.4.4 and emoji-js 3.0.2 and now tagged :+1:

**Comment by jmeas** [comment]
Thanks! :v:
