### ISSUE TITLE
Can I have a demo page ?

### ISSUE THREAD

**Issue by JimishF** [iamcal/js-emoji#64]

**Comment by vinnymac** [comment]
@JimishF A demo page already exists [here](http://unicodey.com/js-emoji/demo/demo.htm). It is also in the readme. Did you mean something else?

**Comment by JimishF** [comment]
Nahh .. Thanks. i didn't found at that time so i issued it.

**Comment by backspace** [comment]
You could close this issue, then, @JimishF!
