### ISSUE TITLE
Keep original unicode emoji

### ISSUE THREAD

**Issue by PranKe01** [iamcal/js-emoji#71]
Hi there,
I need a feature to keep the original unicode emoji after a replace.
I'm using replace_unified to replace my unicode emojis. But after clicking on one smiley I need to add this smiley to a chat-text-input.

For this I changed the function emoji.prototype.replacement:

`if (self.supports_css) {
            if (self.use_sheet && px != null && py != null){
                var mul = 100 / (self.sheet_size - 1);
                var style = 'background: url('+self.img_sets[img_set].sheet+');background-position:'+(mul*px)+'% '+(mul*py)+'%;background-size:'+self.sheet_size+'00%';
                return '<span class="emoji-outer emoji-sizer" data-unicode-smiley="' + self.data[idx][0][0] + '"><span class="emoji-inner" style="' + style + '"' + title + '>' + text + '</span></span>' + extra;
            }else if (self.use_css_imgs){
                return '<span class="emoji emoji-' + idx + '"' + title + ' data-unicode-smiley="' + self.data[idx][0][0] + '">' + text + '</span>' + extra;
            }else{
                return '<span class="emoji emoji-sizer" data-unicode-smiley="' + self.data[idx][0][0] + '" style="background-image:url(' + img + ')"' + title + '>' + text + '</span>' + extra;
            }
        }
        return '<img src="' + img + '" class="emoji" ' + title + ' data-unicode-smiley="' + self.data[idx][0][0] + '"/>' + extra;`

In the data-unicode-smiley attribute I can now catch the original unicode smiley and add in to the text box. Of cource it will not work, if I call the replace_unified function again. Right now the <span> with the emoji will be inserted into the attribute, which destroys the html - I think that such cases should be catched by this library, too!?

**Comment by iamcal** [comment]
how about instead setting something like `data-unicode-codepoint` to the ID of the emoji. that way you can capture that and turn it into the correct character

**Comment by PranKe01** [comment]
Well that way I would need to convert it someway... Don't know how to do that.

**Comment by iamcal** [comment]
to convert to native:

	var cps = element.dataset.codepoints.split('/');
	var str = '';
	for (var i=0; i<cps.length; i++){
		str += String.fromCodePoint('0x'+cps[i]);
	}

**Comment by RobertMenke** [comment]
@iamcal This is a good solution, but I do think the api should support a replacement of the message with the actual unicode rather than escape sequences like the following \ud83d\ude10.

At the moment I'm having to convert the colons to html, and then parse the html for the code points, and the rebuild my message with the actual unicode.

It seems like the API itself could quite easily convert colons to the actual unicode with codepoints. What are your thoughts on this?

**Comment by iamcal** [comment]
this is possible already, just undocumented:

    var emoji = new EmojiConvertor();
    emoji.init_env();
    emoji.replace_mode = 'unified';
    emoji.allow_native = true;

this happens automatically on some/most platforms that support it.

**Comment by RobertMenke** [comment]
@iamcal Thank you for clarifying! I agree that the use case is somewhat limited as the escape sequences work in almost all cases. Hopefully this thread will serve as documentation and help someone that was in a similar situation to me 👍.
