### ISSUE TITLE
Exception when loaded in a hidden iframe on Firefox

### ISSUE THREAD

**Issue by skoda** [iamcal/js-emoji#73]
As a result of this Firefox issue:
https://bugzilla.mozilla.org/show_bug.cgi?id=548397

this line in emoji.js:
var st = window.getComputedStyle(document.body);

causes an exception on the next line if the code is executed within a hidden iframe.

My site only works with css support anyways, so I can patch it for myself easily enough, but I'm not sure what a good fix is in general.

**Comment by skoda** [comment]
Given that the issue is in Firefox (where CSS has basically always been available) you could probably just assume supports_css = true when st === null?

**Comment by iamcal** [comment]
good catch, thanks!
