### ISSUE TITLE
Update emoji-data build as out of date

### ISSUE THREAD

**Issue by mitchcapper** [iamcal/js-emoji#83]
I looked through the sub-module setup a bit, but for some reason js-emoji pulls an older version of your emoji-data repo.  It pulls the version that has an SSH submodule reference which causes builds to fail for this module.  If you can update it to pull master (or at least since that issue has been fixed) that would be great.

**Comment by mitchcapper** [comment]
ah this is fixed by #82

**Comment by iamcal** [comment]
this is now merged to master
