### ISSUE TITLE
can not convert some emoji to colon style string, for example 🤣

### ISSUE THREAD

**Issue by hellogithub2014** [iamcal/js-emoji#84]
I followed the instruction of your demo at [demo](https://unicodey.com/js-emoji/demo/demo.htm) 

When I test In iphone 6, it works just fine if I convert emojis that are very common. But there are still some emojis I can't convert to colon style, their output are still emojis.

For example
* 🤣
* 🤡
* 🤠

my code:
```
var emoji = new EmojiConvertor();

emoji.img_sets = {
	'apple'    : {'path' : '/js-emoji/build/emoji-data/img-apple-64/'   , 'sheet' : '/js-emoji/build/emoji-data/sheet_apple_64.png',    'mask' : 1 },
	'google'   : {'path' : '/js-emoji/build/emoji-data/img-google-64/'  , 'sheet' : '/js-emoji/build/emoji-data/sheet_google_64.png',   'mask' : 2 },
	'twitter'  : {'path' : '/js-emoji/build/emoji-data/img-twitter-64/' , 'sheet' : '/js-emoji/build/emoji-data/sheet_twitter_64.png',  'mask' : 4 },
	'emojione' : {'path' : '/js-emoji/build/emoji-data/img-emojione-64/', 'sheet' : '/js-emoji/build/emoji-data/sheet_emojione_64.png', 'mask' : 8 }
};

emoji.use_sheet = true;
emoji.init_env();
emoji.img_set = 'apple';
emoji.replace_mode = 'unified';
emoji.text_mode = false;
emoji.colons_mode = true;
var str_out = emoji.replace_unified(str_in);
```

**Comment by hellogithub2014** [comment]
What I want alternative is： if can not convert a certain emoji to colon style string, then I can receive a signal, so that I can do something to handle this situation.

**Comment by iamcal** [comment]
these will now work with the latest version - unicode 9 / emoji 4 emoijis were missing

there's unfortunately no way to provide a hook for unknown emoji, because it's really just "any of the 1.1 million codepoints not in the list we know about". there's no way to know a character is "an emoji" without a list of things defined as emoji
