### ISSUE TITLE
size reduction from 1.5 gig for emoji-data?

### ISSUE THREAD

**Issue by mitchcapper** [iamcal/js-emoji#85]
Right now including this package in a package.json requires checking out the entire emoji-data repo which has a large amount of history.  I know #28 discusses creating an npm package and there is https://www.npmjs.com/package/front-js-emoji by a 3rd party but not sure if a stop gap of not the full history was considered (so non sub-module).

This is even though the final build size is only 90 megs.

**Comment by iamcal** [comment]
it's now on npm as `emoji-js`, without any images. My intention is to publish multiple image packages that you can install separately

**Comment by iamcal** [comment]
that work is tracked here: https://github.com/iamcal/emoji-data/issues/84
