### ISSUE TITLE
Smaller download size for image sheet?

### ISSUE THREAD

**Issue by rlafuente** [iamcal/js-emoji#87]
While trying out this library in a desktop browser, I was surprised by a 12MB download for the apple_64 image sheet.

Is there any straightforward way to support use cases that could do with smaller icons than the current 64x64 representations? In my own project, 16x16 would be more than enough.

Ideally, users could be able to specify a subset of emoji to support, but this would imply using single images instead of sheets -- and I suppose that would make this into a full-fledged feature request. It's just that the huge size of the sheet can make this library a tough choice to consider given the significant download size. 

(I fully understand that this shortcoming is probably due to a design choice to be able to support the full set of emoji.)

**Comment by rlafuente** [comment]
I see that the [markdown-it emoji plugin](https://markdown-it.github.io/) seems to address my use case. 

If the limitation mentioned in the previous issue report is indeed a design decision in js-emoji, I'm happy to see this issue closed.

**Comment by iamcal** [comment]
you can use any size you like, just by changing the URLs for the image set you're using. for example:

    emoji.img_sets.apple.path = 'http://my-cdn.com/emoji-apple-16/';
    emoji.img_sets.apple.sheet = 'http://my-cdn.com/emoji-apple-sheet-16.png';

to use the 16px versions

**Comment by rlafuente** [comment]
Oh! I didn't realise it'd be a matter of just switching the picture, I thought the size difference would imply a larger effort. Thank you so much, Cal.

(Incidentally, only after posting this issue did I realise who was behind this project. I grew up on B3ta and it's still one of my favourite site designs, as well as remaining one of the most functional imageboards when it comes to simplicity and efficiency. Thank you for that, and for Flickr and for everything else you've made, you're a serious inspiration.)
