### ISSUE TITLE
missing .css file in NPM module

### ISSUE THREAD

**Issue by siddo420** [iamcal/js-emoji#89]
I installed the npm install but did not find the emoji.css file that is mentioned in demo.

**Comment by iamcal** [comment]
the demo is not included in the npm package - you can find it in the `demo/` subdirectory of this repo

**Comment by jfcere** [comment]
@iamcal although the css is available in the demo folder, only including `emoji.js` file does not display css and spritesheet emojis at all. IMHO the `emoji.css` file in the demo is kind of a "must have" in those cases... wouldn't it be a good idea to include it in the distributed package?

**Comment by iamcal** [comment]
that's a good point - i've added it into the `lib/` directory, so that it will be included in future packages

**Comment by jfcere** [comment]
Thanks! 

On the same note... as a quick suggestion, you should remove the CSS file from the demo folder and link your demo to the `lib/emoji.css` to avoid maintaining two files and it will prove it work at the same time ... just saying 😄 

https://github.com/iamcal/js-emoji/blob/202a66471f507709ad658685283ddcac01d0c130/demo/demo.htm#L7

**Comment by iamcal** [comment]
i avoided doing that because it will break backward compatibility for anybody not using the package. it's something i might do when we next do a major version bump, but for now it doesn't hurt much to have it duplicated

**Comment by jfcere** [comment]
you're a wise man 😉
