### ISSUE TITLE
Import emoji from 'emoji-js'

### ISSUE THREAD

**Issue by clemishow** [iamcal/js-emoji#94]
Hello,

I tried to import in a Angular 2 / Typescript project.

```
import * as emoji from 'emoji-js';
```

There is no error.

```javascript
// console.log(emoji);
    ƒ (){

		var self = this;

		/**
		 * The set of images to use for graphical emoji.
		 *
		 * @memberof emoji
		 * @type {string}
		 */
		self.img_set = 'apple';

		/**
		 * Configuration details for d…
```

But when I do a `emoji.init_env()` for example I got this error : 

```
TypeError: __WEBPACK_IMPORTED_MODULE_7_emoji_js__.init_env is not a function
```
Can you help me please ? Thank you

**Comment by iamcal** [comment]
did you create an instance of the emoji object first?

`var emoji = new EmojiConvertor();`

**Comment by clemishow** [comment]
Yes, but with Typescript, it says immediately : Emoji Converter undefined

**Comment by nosugarsociety** [comment]
I have same situation. Tried to import 'emoji-js' and checked out emoji.js file successfully compiled to my bundle.js (using Webpack ) but EmojiConverter still not defined. Of course, I created instance of emoji object.

**Comment by ChrisOwen101** [comment]
I used this (although I'm using React) and it worked for me:
import EmojiConvertor from 'emoji-js';

**Comment by mentos1386** [comment]
i had to use `import * as EmojiConvertor from 'emoji-js/lib/emoji.js';` on angular 5.

**Comment by vishnukalakota** [comment]
@ChrisOwen101 
import EmojiConvertor from 'emoji-js'; 
works only remote debugger on. 
Emoji Converter undefined when disable the debugger on simolator

**Comment by xanderberkein** [comment]
@vishnukalakota If you are using react native, this pull request will fix your problems: https://github.com/iamcal/js-emoji/pull/106
