### ISSUE TITLE
"use strict" at the function level 

### ISSUE THREAD

**Issue by colingreene28** [iamcal/js-emoji#97]
Can we enforce strict mode at the function level rather than the script level? Pulling in this library forces your existing code base to adhere to strict mode, which isn't normally an issue but I found that IE11 didn't like it.

I've had to fork this package and make the changes myself to test it out. Seems to work fine.

I can make a PR if that will expedite the process?

Cheers

**Comment by iamcal** [comment]
can you send a PR? thanks
